#!/bin/sh

size=5000

for insert in L A B R S V
do
	for order in A P R
	do
		if false  #$order == "R" ]
		then
			for seed in 1 2 3 4
			do
				echo ""
				echo "Test: ./tlabM $size $order $insert $seed"
				echo "t" | ./tlabM $size $order $insert $seed | grep -v Tree
			done
		else
			echo ""
			echo "Test: ./tlab $size $order $insert"
			echo "t" | ./tlab $size $order $insert | grep -v Tree
		fi
	done
done
